### ISSUE TITLE
How can i run with this sudoku.c file

### ISSUE THREAD

**Issue by tony8888lrz** [crvargasm/Sudoku-Solution-Validator#1]

**Comment by crvargasm** [comment]
with a C compiler... 

For example in Linux u can use the next command when u are positioned at the same level of "sudoku.c" file:
`gcc -o sudoku sudoku.c`
 
then you run:
`./sudoku`

**Comment by tony8888lrz** [comment]
🆗, i got it, the gcc version is not right, I have to move the all `for(int i = 0)` loop -> `for(i = 0)`
and for we should add
`gcc sudoku.c -lpthead` 
when dealing with the multi threads.

**Comment by tony8888lrz** [comment]
Anyway, thanks
